### 9 Most Important Application of Linear Algebra
1. Data Set and Data Files
2. Images and Photographs
3. Data Preparation: Examples are Dimensionality reduction and hot encoding (used for encoding categorical variables)
4. Linear Regression
5. Regularization: Used to prevent over fitting
6. Principal Component Analysis (PCA): Used to reduce number of columns of a dataset
7. Latent Semantic Analysis (LSA): Used for keyword categorization, i.e. documents are represented as a large matrices of words occurrences
8. Recommender Systems
9. Deep Learning

Vector = Matrix, because it has dimensionality. It's an ordered list of numbers
### Python Representation of a Vector:
- rowVector = np.array([[1,2,3,4,5] ])
- columnVector = np.array([[1],[2],[3],[4],[5]])
- These two vectors are not the same.

Watch this YouTube Video https://youtu.be/l9ioZA9brtc

### Vector Addition & Subtraction
Addition is only possible for two vectors with the same dimension

In [18]:
import numpy as np

a = np.array([20, 40, 60])
b = np.array([10, 20, 30])
c = np.array([5, 10, 15, 20])

In [19]:
# The Code below should run because a and b has same dimension
a+b

array([30, 60, 90])

In [20]:
# The following code should fail because a and c has different dimension
# a+c

In [21]:
# The following code should fail because a and c has different dimension
# a-c

In [22]:
a*b

array([ 200,  800, 1800])

In [23]:
a/b

array([2., 2., 2.])

In [24]:
scalar = 2
list_a = [10,11,12,13,14,15]
print(list_a)
list_as_array = np.array(list_a)
print(list_as_array)

[10, 11, 12, 13, 14, 15]
[10 11 12 13 14 15]


In [25]:
# This is not an operation of scalar vector multiplication, list_a is not a vector
scalar * list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [26]:
# Only when a vector is stored as an nd array do they have element wise multiplication
scalar * list_as_array

array([20, 22, 24, 26, 28, 30])

### Vector Projections and Basics
#### Dot Product of Vectors

\begin{aligned}
Formula:a.b &= \sum_{i=1}^{n}a_ib_i \\
\bar{a} &= \left[1,2,3,4,5\right] \\
\bar{b} &= \left[6,7,8,9,10\right] \\
a.b &= 1.6 + 2.7 + 3.8 + 4.9 + 5.10 &= 130 \\
\end{aligned}


In [27]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.array([11,12,13,14,15])

#### Basic Properties of Dot Product
- It is commutative: a.b = b.a
- It is distributive: a(b + c) = a.b + a.c

In [28]:
# Dot product of vectors
print(np.dot(a,b))
print(np.dot(b,a))

130
130


In [29]:
first_result = np.dot(a, b+c)
print(first_result)
second_result = np.dot(a,b) + np.dot(a,c)
print(second_result)

335
335


#### Magnitude of a Vector

\begin{aligned}
Formula:\left|x\right| &= \sqrt{\sum_{i=1}^{n}x_i^2} \\
\bar{x} &= \left[1,2,3,4,5\right] \\
\left|x\right| &= \sqrt{1^2+2^2+3^3+4^2+5^2}  &= 7.4 \\
\end{aligned}

In [30]:
magnitude = np.linalg.norm(a)
print(magnitude)

7.416198487095663


#### Scalar and Vector Projection

\begin{aligned}
Formula:proj_b a &= \frac{a.b}{\left|b\right|^2}b
\end{aligned}

In [31]:
from numpy import linalg as lng
a = np.array([10,20,30,40,50])
b = np.array([60,70,80,90,100])

In [32]:
magnitude = lng.norm(a)
print(magnitude)

74.16198487095663


In [33]:
vector_projection = (np.dot(a,b)/np.dot(b,b)) * b
print(vector_projection)

[23.63636364 27.57575758 31.51515152 35.45454545 39.39393939]
